//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWProject.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> ProfilePicId { get; set; }
        public bool HasParent { get; set; }
        public int HierarchyId { get; set; }
        public Nullable<int> HierarchyParent { get; set; }
        public string Introduction { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public Nullable<byte> Priority { get; set; }
    
        public virtual Img_DataFiles Img_DataFiles { get; set; }
    }
}
