//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWProject.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doubt
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Enable { get; set; }
        public bool IsExterior { get; set; }
        public Nullable<System.Guid> ExteriorId { get; set; }
        public Nullable<bool> Type { get; set; }
    
        public virtual User User { get; set; }
    }
}
