//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWProject.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_DataFiles
    {
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string FileExtention { get; set; }
        public Nullable<int> Size { get; set; }
        public System.Guid UserId { get; set; }
        public string Caption { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.Guid> ImgId { get; set; }
    
        public virtual Img_DataFiles Img_DataFiles { get; set; }
        public virtual User User { get; set; }
    }
}
