//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWProject.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Ip { get; set; }
        public string Browser { get; set; }
        public string VirtualPath { get; set; }
        public string UserAgent { get; set; }
        public string UrlRefferer { get; set; }
        public string Url { get; set; }
        public string RequestType { get; set; }
        public string ResponseStatus { get; set; }
        public Nullable<bool> Type { get; set; }
    }
}
