//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWProject.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper_DataFiles
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Introduction { get; set; }
        public string Body { get; set; }
        public string Authors { get; set; }
        public string Conclution { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public System.Guid PostId { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
