//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWProject.Models.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Paper_DataFiles = new HashSet<Paper_DataFiles>();
            this.Media_DataFiles = new HashSet<Media_DataFiles>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public byte Type { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.Guid> ProfilePicId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Enable { get; set; }
        public Nullable<System.DateTime> OnlineDate { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public System.Guid UserId { get; set; }
        public bool IsIndex { get; set; }
    
        public virtual Img_DataFiles Img_DataFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper_DataFiles> Paper_DataFiles { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Media_DataFiles> Media_DataFiles { get; set; }
    }
}
